config/routes.rb
OverflowClone::Application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  # get 'vote', to: 'answers#vote', as: 'vote'

  match('vote/:id', {:via => :get, :to => 'answers#vote'})


  root to: "posts#index"
  resources :sessions, :only => [:new, :create, :destroy]
  resources :users


  resources :posts do
    resources :answers, :only => [:new, :create]
  end

  resources :answers, :only => [:destroy, :edit, :update]

end

app/models/answer.rb
require 'pry'
class Answer < ActiveRecord::Base
  validates :answer, presence: true
  belongs_to :user
  belongs_to :post

    def  mark_best_answer
      self.update(:best_answer => true)
    end
    def self.remove_best_answer
      Answer.all.each do |answer|
        if answer.best_answer == true
          answer.update(:best_answer => false)
        end
      end
    end
  end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :answers
  validates :name, presence: true
  validates :comment, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :name, presence: true
  validates :name, uniqueness: true
  has_many :posts
  has_many :answers

def self.authenticate(user_name, password)
    user = find_by_user_name(user_name)
    return user if user && user.authenticate(password)
  end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def new
    @post = Post.find(params[:post_id])
    @answer = Answer.new
  end

  def create
    @post = Post.find(params[:post_id])
    @answer = Answer.new(answer_params)

    if @answer.save
      @answer.update(:user_id => current_user.id)
      @post.answers << @answer
      @answer.update(:best_answer => false)
      flash[:notice] = "Answer Added"
      respond_to do |format|
        format.html { redirect_to :back }
        format.js
      end
    else
      respond_to do |format|
        format.html { redirect_to :back }
        format.js { render 'new' }
      end
    end
  end

  def edit
    @answer = Answer.find(params[:id])
  end

  def update
    @answer = Answer.find(params[:id])

    if @answer.update(answer_params)
      flash[:notice] = "Answer Updated"
      redirect_to user_path(current_user)
    else
      render 'edit'
    end
  end

  def vote
    target_answer = Answer.find(params[:id])
    Answer.remove_best_answer
    target_answer.mark_best_answer
    redirect_to root_path

  end
  def destroy
    @answer = Answer.find(params[:id])
    @answer.destroy
    redirect_to user_path(current_user)
  end

  def answer_params
    params.require(:answer).permit(:answer)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
   def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_filter :authorize, only: [:new, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      current_user.posts << @post
      respond_to do |format|
        format.html { redirect_to :back }
        format.js
      end
    else
       respond_to do |format|
        format.html { redirect_to users_path(current_user) }
        format.js {render 'new'}
      end
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private
    def post_params
      params.require(:post).permit(:name, :comment)
    end
end

app/controllers/sessions_controller.rb
class SessionsController< ApplicationController

  def new
  end

  def create
    user = User.find_by_name(params[:name])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path(current_user), notice: "Logged in!!!"
    else
      flash.now.alert = "User name or password is invalid."
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!!!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  before_filter :authorize, only: [:edit, :update, :destroy, :show]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user), notice: "Thank you for signing up"
    else
      render 'new'
    end
  end

  def show

    @user = User.find(params[:id])
  end
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "Updated"
      redirect_to root_path
    else
      render "edit"
    end
  end

  def destroy
    session[:user_id] = nil
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path

  end

private
  def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/_form.html.erb
<%= render("layouts/errors", :object => @post) %>

<div id="new_answer">
  <%= form_for [@post, @answer], remote: true do |f| %>
    <div class="form-group">
      <%= f.label :answer %></br>
      <%= f.text_area :answer %>
    </div>

    <%= f.submit(:class => "btn btn-primary") %>
  <% end %>
</div>

app/views/answers/create.js.erb
$('#new_answer_link').show();
$('.error_messages').remove();
$('#new_answer').remove();

$('#answer_list').append(' <li> <%= @answer.answer %> </li>');

app/views/answers/edit.html.erb
<h1>Edit Answer<h2>

<%= form_for [@answer] do |f| %>
  <div class="form-group">
    <%= f.label :answer %></br>
    <%= f.text_area :answer %>
  </div>

  <%= f.submit(:class => "btn btn-primary") %>
<% end %>

app/views/answers/new.html.erb
<%= render("form") %>

app/views/answers/new.js.erb
$('#new_answer').remove()
$('#new_answer_link').hide().after('<%= j render("form") %>');

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div class="error_messages">
    <h2>Form is invalid</h2>
     <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OverflowClone</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse" role="navigation">
  <span class="logo">OverFlow Clone</span>
  <span class="pull-right">
    <%= link_to "Main Page", root_path %> |
    <%= link_to "Sign Up", signup_path %> |
    <% if current_user.nil? %>
      <%= link_to "Login", login_path %> |

    <% else %>
      <%= link_to "Add New User", signup_path %> |
      <%= link_to "Logout", logout_path %> |
      <%= link_to "Profile", user_path(current_user) %>

    <% end %>

  </span>
</nav>

<%= flash[:notice] %>
<%= flash[:alert] %>
<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/posts/_form.html.erb
<%= render("layouts/errors", :object => @post) %>
<div id="post_form">
  <%= form_for @post, remote: true do |f| %>
    <div class="form-group">
      <%= f.label :name, "Title" %></br>
      <%= f.text_field :name %>
    </div>
    <div class="form-group">
      <%= f.label :comment, "Question" %></br>
      <%= f.text_area :comment %>
    </div>


    <%= f.submit(:class => "btn btn-primary") %>
  <% end %>
</div>

app/views/posts/create.js.erb
$('#new_post_link').show();
$('.error_messages').remove();
$('#new_post').remove();

$('#post_list').append('<li> <%= @post.name %> : <%= @post.comment %><%= link_to "Edit Post | ", edit_post_path(@post) %> <%= link_to "Delete Post", post_path(@post),
                           :confirm => "You sure?",
                           :method => "delete" %> </li>');

app/views/posts/edit.html.erb
<h1>Edit<h1>
<%= render('form') %>

app/views/posts/index.html.erb
<h1>Here are the current posts</h1>



<ol>
  <% @posts.each do |post| %>
    <li>
        <%= link_to  "#{post.name}", post_path(post) %>
    </li>
  <% end %>
</ol>

app/views/posts/new.html.erb
<h1>Enter Question:</h1>

<div id="new_post">
<%=render('form')%>
</div>

app/views/posts/new.js.erb
$('#post_form').remove();
$('#new_post_link').hide().after('<%= j render("form") %>');

app/views/posts/show.html.erb
<h1><%= @post.name%></h1>
<h4><%= @post.comment %></h4>

<ul id="answer_list">
  <% @post.answers.each do |answer| %>
    <li><%= answer.answer %>
      <% if current_user.id == answer.user.id %>
      <%= link_to "Vote as Best", controller: "answers", action: "vote", id: answer.id %>
      <% end %>
    </li>
  <% end %>
</ul>


<% if current_user %>
  <%= link_to "Add an Answer", new_post_answer_path(@post), id: "new_answer_link", remote: true %>

<% end %>

app/views/users/_form.html.erb
<%= render("layouts/errors", :object => @user) %>

<%= form_for @user do |f| %>
  <div class="form-group">
    <%= f.label :name %></br>
    <%= f.text_field :name %>
  </div>

  <div class="form-group">
    <%= f.label :password %></br>
    <%= f.password_field :password %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation %></br>
    <%= f.password_field :password_confirmation %>
  </div>

  <%= f.submit(:class => "btn btn-primary") %>
<% end %>
<br>

app/views/users/edit.html.erb
<h1>Edit Your Profile<h1>
  <%= render('form') %>

app/views/users/new.html.erb
<h1>Sign up page</h1>

<%= render('form') %>

app/views/users/show.html.erb
<h1>Welcome <%= @user.name %></h1>


<h2>Your Posts</h2>

  <ul id="post_list">
    <% if @user.posts.length != 0 %>
      <% @user.posts.each do |post| %>

            <li><div class="col-md-6"><%= link_to "#{post.name}: ", post_path(post)%> </div>
                <div class="col-md-3"><%= link_to "Edit Post | ", edit_post_path(post) %> <%= link_to "Delete Post", post_path(post),
                           :confirm => "You sure?",
                           :method => "delete" %></div> </li>

        <% end %>

    <%end%>
 </ul>
<h2>Your answers</h2>
  <% if @user.answers.length != 0 %>

        <% @user.answers.each do |answer|%>
          <li> <%= answer.answer%> <%= link_to "Edit Answer | ", edit_answer_path(answer) %> <%= link_to "Delete Answer", answer_path(answer), :confirm => "You sure?", :method => "delete" %> </li>

          </li>

    <%end%>
  <% end %>
</ul>



<%= link_to "Create a new post", new_post_path, id: "new_post_link", remote: true, :class => "btn btn-info" %>



<nav class="navbar navbar-fixed-bottom" role="navigation">
<p><%= link_to "Edit this user", edit_user_path(@user)%>
       <%= link_to "Delete this user", user_path(@user),
                         :confirm => "You sure?",
                         :method => "delete" %></p>
</nav>